### ISSUE TITLE
Generated links in the emails alerts seem to be broken

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/notification-system#1]
![image](https://user-images.githubusercontent.com/1452968/42068877-c92679ae-7b91-11e8-9966-8ddddb838b6c.png)

The file does exist in the dropbox account. 

Maybe the links have a timeout? Are we generating permalinks?

CC @proe

**Comment by mitchazj** [comment]
Pretty sure the current links do have a timeout 👍 

I think you can generate permanent links with `sharing_create_shared_link_with_settings(file_path).url`, however this function only works once on any particular file & after that will return an error (because the link has already been created)

As a result it might be necessary to permanently store links created via that endpoint in the filesystem - I think you technically can retrieve previously created links with `sharing_list_shared_links` but it might be inefficient in the long run to do so.

**Comment by atruskie** [comment]
Cheers @mitchazj - that'll save me a bit of time
